post_install() {
	systemctl enable systemd-networkd systemd-resolved

	# systemd-resolved's resolv.conf
	mv /etc/resolv.conf{,.pacsave}
	ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

	# Common site-local code mounted from host
	mkdir /usr/src/modules

	# To fix "login[29]: pam_securetty(login:auth): access denied: tty 'pts/0' is not secure !"
	echo >>/etc/securetty
	echo pts/0 >>/etc/securetty
}
